# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 33d70624d596c695ad93279743ea533ddead13b0039fb7fb0e78df91b5207fdac6514628ba5c7b3a6920ee0a1de1a08d069d1132fb79bc3244db349a669d87e3

test:
  secret_key_base: 3df0aaac929ebc95eda3588c280b0842ed5295b007d2be537612149ff1d3c615e5b5885c186a04d5feb2757d17b597be2b5851589e9dea14ea4132162fe7f28b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
